# Generated by Django 5.1.7 on 2025-03-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
